import { createEngine } from "edgplay";
import { ChessRoom } from "./ChessRoom.js";

const engine = createEngine()
  .register("chess", ChessRoom);

// The Worker fetch handler — all routing handled by the framework
export default engine.worker;

// Static DO exports required by Cloudflare — generated by the framework
// These names must match class_name in wrangler.jsonc
export const { GameRoom, LobbyDO } = engine.durableObjects;
